![homework](homework.png)

In [17]:
import numpy as np
import math

In [2]:
def initialization(n):
    bn = range(1,n+1)
    An = []
    for i in range(n):
        list = range(1,n+1)
        list[i] = n**2
        An.append(list)
    return An,bn

In [56]:
class iteration():
    def __init__(self):
        self.A = None
        self.b = None
        self.x0 = None
    # 构造迭代矩阵An和初始值x0 和bn。
    def initialization(self,n):
        self.b = range(1,n+1)
        self.A = []
        self.x0 = np.zeros((n,))
        for i in range(n):
            list = range(1,n+1)
            list[i] = n**2
            self.A.append(list)
#         return self.An,self.bn,self.x0
    
    def jacoby(self):
        print 'h'
        

In [59]:
it = iteration()
print it.initialization(4)
it.A
it.b

None


[1, 2, 3, 4]

In [5]:
A = np.array(it.An)
b = np.array(it.bn)
print A,'\n',b

[[16  2  3  4]
 [ 1 16  3  4]
 [ 1  2 16  4]
 [ 1  2  3 16]] 
[1 2 3 4]


分解矩阵A得到L和U。

In [54]:

def LU_decompose(A):
    length = len(A)
    print length
    L = np.zeros((length,length))
    U = np.zeros((length,length))
#     print L.dtype,U.dtype
    # 初始化向量
    for i in range(len(A)):
        U[0][i]=A[0][i]
        L[i][0]=A[i][0]*1.0/U[0][0]
    for r in range(1,len(A)):
        for i in range(r,len(A)):
            sum1 = 0
            sum2 = 0
            for k in range(0,r):
                sum1 +=L[r][k]*U[k][i]
                sum2 +=L[i][k]*U[k][r]
            U[r][i] = A[r][i]-sum1
            L[i][r] = (A[i][r]-sum2)*1.0/U[r][r]
    return L,U

In [55]:
L,U = LU_decompose(A)
L = np.array(L)
U = np.array(U)
print L,'\n',U

4
[[ 1.          0.          0.          0.        ]
 [ 0.0625      1.          0.          0.        ]
 [ 0.0625      0.11811024  1.          0.        ]
 [ 0.0625      0.11811024  0.1602238   1.        ]] 
[[ 16.           2.           3.           4.        ]
 [  0.          15.875        2.8125       3.75      ]
 [  0.           0.          15.48031496   3.30708661]
 [  0.           0.           0.          14.77721261]]


利用分解得到的LU来回代求得精确解。

In [8]:
def solve(L,U,b):
    length = len(L)
    y = np.array([0.0]*length)
    x = np.array([0.0]*length)
    print x.dtype,y.dtype
    n = len(x)-1
#     print len(y)
    y[0] = b[0]
    for i in range(1,len(y)):
        sum1 = 0
        for k in range(0,i):
            sum1 += L[i,k]*y[k]*1.0
        y[i]= b[i]-sum1
    x[n] = y[n]*1.0/U[n,n]
    for i in range(n-1,-1,-1):
        sum2 = 0
        for k in range(i+1,n+1):
            sum2+= U[i,k]*x[k]
        x[i] = (y[i]-sum2)*1.0/U[i][i]*1.0
    return y,x

In [9]:
solve(L,U,b)

float64 float64


(array([ 1.        ,  1.9375    ,  2.70866142,  3.27466938]),
 array([-0.02271789,  0.04708798,  0.12763321,  0.22160264]))

In [10]:
y= np.linalg.solve(L, b)
x = np.linalg.solve(U,y)
print y,x

[ 1.          1.9375      2.70866142  3.27466938] [-0.02271789  0.04708798  0.12763321  0.22160264]


In [14]:
np.linalg.solve(A,b)

array([-0.02271789,  0.04708798,  0.12763321,  0.22160264])

In [37]:
def jacoby(A,b,x):
    n = len(b)
    x0=np.array([0.0]*n)
    x1 = np.array([0.0]*n)
    count = 0
    while(True):
        count +=1
        for i in range(0,n):
            sum1 =0
            for j in range(0,n):
                if(j!=i):
                    sum1 +=A[i,j]*x0[j]
            x1[i] = (b[i]-sum1)*1.0/A[i,i]
        e = max(abs(x1-x))
        if(e<1.0/2*(10**(-4))):
            break
        else:
            x0 = x1
    return count,x1

In [38]:
jacoby(A,b,x)

(5, array([-0.02271687,  0.04710775,  0.12763533,  0.22159971]))

In [49]:
def  Seidel(A,b,x):
    n = len(b)
    x0=np.array([0.0]*n)
    x1 = np.array([0.0]*n)
    count = 0
    while(True):
        count +=1
        for i in range(0,n):
            sum1 =0
            for j in range(0,n):
                if(j<i):
                    sum1 +=A[i,j]*x1[j]
                elif(j>i):
                    sum1 +=A[i,j]*x0[j]
            x1[i] = (b[i]-sum1)*1.0/A[i,i]
        e = max(abs(x1-x))
        if(e<1.0/2*(10**(-4))):
            break
        else:
            x0 = x1
    return count,x1

In [50]:
Seidel(A,b,x)

(5, array([-0.02270494,  0.0470889 ,  0.12762894,  0.22160252]))

In [51]:
def Sor(A,b,x,w):
    n = len(b)
    x0=np.array([0.0]*n)
    x1 = np.array([0.0]*n)
    count = 0
    while(True):
        count +=1
        for i in range(0,n):
            sum1 =0
            for j in range(0,n):
                if(j<i):
                    sum1 +=A[i,j]*x1[j]
                elif(j>=i):
                    sum1 +=A[i,j]*x0[j]
            x1[i] = x0[i]+w*1.0*(b[i]-sum1)*1.0/A[i,i]
        e = max(abs(x1-x))
        if(e<1.0/2*(10**(-4))):
            break
        else:
            x0 = x1
    return count,x1

In [53]:
wn = [0.6,0.8,1.0,1.2]
for w in wn:
    print Sor(A,b,x,w)

(12, array([-0.0227142 ,  0.04710403,  0.12766402,  0.22157572]))
(8, array([-0.02272497,  0.0470859 ,  0.12765072,  0.22159499]))
(5, array([-0.02270494,  0.0470889 ,  0.12762894,  0.22160252]))
(7, array([-0.02275042,  0.04708037,  0.12765342,  0.22161188]))
