In [5]:
import numpy as np

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2.dtype
arr1.dtype
arr1.shape

(5,)

In [20]:
np.empty(10)
np.eye(10)
np.int
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [10]:
arr = np.arange(32).reshape((8, 4))
print arr
a = arr[:,1]
print a
a[:]= 0
arr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 1  5  9 13 17 21 25 29]


array([[ 0,  0,  2,  3],
       [ 4,  0,  6,  7],
       [ 8,  0, 10, 11],
       [12,  0, 14, 15],
       [16,  0, 18, 19],
       [20,  0, 22, 23],
       [24,  0, 26, 27],
       [28,  0, 30, 31]])